StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{64EA18C6E17FFDCE}" {
   Id "SPC-AmmunitionID_73mm"
   Target_en_us "73x285mmR"
   Modified 1693064362
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{64EA18C705C8E454}" {
   Id "SPC-AmmunitionID_OG9"
   Target_en_us "OG-9"
   Modified 1693064106
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{64EA18C70255C2D0}" {
   Id "SPC-AmmunitionID_PG9"
   Target_en_us "PG-9"
   Modified 1693064112
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{60F08A876C6DF5A9}" {
   Id "SPC-Vehicle_BMP1_Name"
   Target_en_us "BMP-1 Infantry Fighting Vehicle"
   Modified 1626377723
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
  }
  CustomStringTableItem "{60F08A8771CE02CF}" {
   Id "SPC-Vehicle_BMP1P_Name"
   Target_en_us "BMP-1P Infantry Fighting Vehicle"
   Modified 1626377730
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
  }
  CustomStringTableItem "{64EA18C6FC47C764}" {
   Id "SPC-Weapon_2A28_Description"
   Target_en_us "2A28"
   Modified 1693063553
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{64EA18C6FB94329B}" {
   Id "SPC-Weapon_2A28_Name"
   Target_en_us "2A28"
   Modified 1693064157
   Author "mikia"
   LastChanged "mikia"
  }
 }
}